services:
  postgres:
    image: postgres:16-alpine
    container_name: evently-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: evently_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evently-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evently-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      APP_NAME: Evently
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "http://localhost:8080"
      APP_KEY: base64:eZgqYmFzZTY0OnN1cmFiYXlhZGV2MTJzZWNyZXQ=
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: evently_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      MIDTRANS_MERCHANT_ID: G441882517
      MIDTRANS_CLIENT_KEY: SB-Mid-client-Qx6UwA5DFHHUPt2B
      MIDTRANS_SERVER_KEY: SB-Mid-server-pk8dlBip3clCK6pGOmkSAF18
      MIDTRANS_IS_PRODUCTION: "false"
    ports:
      - "8080:8080"
    networks:
      - evently-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: evently-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5177:80"
    networks:
      - evently-net

volumes:
  postgres_data:

networks:
  evently-net:
    driver: bridge
